// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// inflect_iqr_cpp
double inflect_iqr_cpp(NumericVector x);
RcppExport SEXP _fastINFLECT_inflect_iqr_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(inflect_iqr_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// inflect_dip_pvalue_cpp
NumericVector inflect_dip_pvalue_cpp(NumericVector D, IntegerVector n, NumericMatrix qd, IntegerVector nn, NumericVector Ps);
RcppExport SEXP _fastINFLECT_inflect_dip_pvalue_cpp(SEXP DSEXP, SEXP nSEXP, SEXP qdSEXP, SEXP nnSEXP, SEXP PsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type D(DSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type n(nSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type qd(qdSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nn(nnSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Ps(PsSEXP);
    rcpp_result_gen = Rcpp::wrap(inflect_dip_pvalue_cpp(D, n, qd, nn, Ps));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fastINFLECT_inflect_iqr_cpp", (DL_FUNC) &_fastINFLECT_inflect_iqr_cpp, 1},
    {"_fastINFLECT_inflect_dip_pvalue_cpp", (DL_FUNC) &_fastINFLECT_inflect_dip_pvalue_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_fastINFLECT(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
