#' @title Run the fastINFLECT computation
#'
#' @description Wrapper function combining all aspects of the fastINFLECT
#' reimplementation: iterative metaclustering, marker-unimodality testing, and
#' inflection point determination. The exported function is still named
#' `INFLECT()` for continuity with the original INFLECT API, but the package
#' now uses a memoised, benchmarked engine that avoids the original repeated
#' per-k QC loop.
#' Default options include fewer calculations at higher cluster numbers, zeroes
#' are removed and inflection point is calculated on the fitted curve.
#'
#' @param FlowSOM.results A supported SOM object with completed SOM clustering. Supports \pkg{FlowSOM} objects and \pkg{kohonen} objects returned by \code{\link[kohonen]{som}} or \code{\link[kohonen]{xyf}}.
#' @param set.i Vector containing either the desired iterations to be tested, or if \code{length(set.i)==2}, the point where iterations are spaced apart by 5 or 10. Intended to limit computation time
#' @param multicore logical, should the QC sweep be run in parallel (fork-based \code{\link[parallel]{mclapply}} over distinct SOM-node subtrees on Unix). Ignored on Windows.
#' @param cores If \code{multicore == TRUE}, number of cores to be used. If \code{NULL} max number of cores-1 is used
#' @param zeroes.in Should be values at and below \code{0} be included. Recommeded default is \code{FALSE}
#' @param only.clustering.markers If \code{TRUE} only evaluates markers specified as clustering markers. For \pkg{kohonen} objects this is the first data layer.
#' @param acquired_markers Vector of column names with marker data to be evaluated by fastINFLECT. Ignored if \code{only.clustering.markers == TRUE}
#' @param basedata Data to be used to calculate inflection point, given as a string. Options are \code{Curve} and \code{Points}
#' @param ggtitle Optional title for resulting diagnostic graph. Default \code{NULL}
#' @param uniform.test What tests are performed per marker per cluster. Options are \code{"both"}, \code{"spread"}, or \code{"unimodality"}.
#' @param th.pvalue Threshold for rejecting the unimodality \link[diptest]{dip.test} result. Default is \code{0.05}.
#' @param th.IQR Threshold for rejecting marker distribution based on inter-quartile range. Default is arc-sinh transformed value of \code{2}.
#' @param max.n.diptest Optional integer cap on the number of events used per (cluster, marker) dip test. Because the dip test's power grows with sample size, large clusters otherwise reject unimodality for negligible deviations, biasing the score. Setting a cap (e.g. \code{2000}) makes the score size-robust. Subsampling is seeded and deterministic. Default \code{NULL} preserves the legacy scoring path.
#' @param seed Integer base seed for the optional \code{max.n.diptest} subsampling. Default \code{1L}.
#' @param target Target unimodality (fraction in \code{(0,1]} or percentage in \code{(1,100]}) used to report the smallest k with no residual bimodal clusters. Default \code{0.95}. See \code{\link{inflect_threshold_k}}.
#' @param verbose \code{logical}, default is \code{FALSE}.
#' @param ... Arguments to pass to \code{\link[diptest]{dip.test}} through \code{\link{FlowSOMQC}}.
#'
#' @return An S3 \code{inflect.results} object containing a dataframe with Unimodality scores, a dataframe with the fitted curve, the \code{\link{Lfunction}} results, the diagnostic \pkg{ggplot2} plot, the \code{list} of metaclusterings performed during \code{\link{iteration.metacluster}}, a \code{list} of accuracy matrices generated by \code{\link{FlowSOMQC}}, and a \code{selection} data frame giving the recommended number of metaclusters under three criteria (LL.4 inflection, \code{\link{inflect_kneedle}} knee, and the \code{\link{inflect_threshold_k}} target).
#' Running the individual function \code{\link{iteration.metacluster}} and \code{\link{QC.to.curve}} might provide more options and flexibility.
#'
#' @seealso \code{\link{iteration.metacluster}}, \code{\link{iteration.QC}}, \code{\link{FlowSOMQC}}, \code{\link{QC.to.curve}}, \code{\link{leastError}}, \code{\link{Lfunction}}, \code{\link{marker.performance}}
#'
#' @examples
#'
#' # Read in FlowSOM object from file. Downsampled clustering result of Levine32 dataset clustering.
#' # SOM-clustered to 375 clusters.
#' flowsom <- system.file("extdata", "Levine32sample.Rdata", package="fastINFLECT")
#' load(flowsom)
#' set.i<- 5:12
#' inflect.results<- INFLECT(FlowSOM.results= dataset, set.i= set.i, multicore=FALSE, zeroes.in=FALSE)
#'
#' # Display diagnostic graph
#' inflect.results$ggplot
#'
#' @export
INFLECT <-
  function(FlowSOM.results,
           set.i = c(150, 200),
           multicore = TRUE,
           cores = NULL,
           zeroes.in = FALSE,
           only.clustering.markers = TRUE,
           acquired_markers = NULL,
           basedata = "Curve",
           ggtitle = NULL,
           uniform.test = c("both", "spread", "unimodality"),
           th.pvalue = 0.05,
           th.IQR = 2,
           verbose = FALSE,
           max.n.diptest = NULL,
           seed = 1L,
           target = 0.95,
           ...) {
    start_time <- proc.time()[["elapsed"]]
    diptest_args <- list(...)
    uniform.test <- match.arg(uniform.test)
    FlowSOM.results <- as_inflect_som(FlowSOM.results)

    set.i <- normalize_set_i(set.i, FlowSOM.results)
    markers <- resolve_inflect_markers(
      FlowSOM.results = FlowSOM.results,
      only.clustering.markers = only.clustering.markers,
      acquired_markers = acquired_markers
    )

    metaclustering.list <-
      iteration.metacluster(
        FlowSOM.results = FlowSOM.results,
        set.i = set.i,
        multicore = multicore,
        cores = cores
      )

    collection.U <-
      iteration.QC(
        FlowSOM.results = FlowSOM.results,
        metaclustering.list = metaclustering.list,
        set.i = set.i,
        multicore = multicore,
        cores = cores,
        zeroes.in = zeroes.in,
        only.clustering.markers = only.clustering.markers,
        acquired_markers = acquired_markers,
        uniform.test = uniform.test,
        th.pvalue = th.pvalue,
        th.IQR = th.IQR,
        max.n.diptest = max.n.diptest,
        seed = seed,
        verbose = verbose,
        ...
      )


    diagnostic.graph <-
      QC.to.curve(collection.U = collection.U,
                  basedata = basedata,
                  ggtitle = ggtitle)

    selection <- .inflect_selection(
      collection.U = diagnostic.graph$collection.U,
      lfunction = diagnostic.graph$lfunction,
      target = target
    )

    provenance <- build_inflect_provenance(
      FlowSOM.results = FlowSOM.results,
      set.i = set.i,
      uniform.test = uniform.test,
      th.pvalue = th.pvalue,
      th.IQR = th.IQR,
      zeroes.in = zeroes.in,
      basedata = basedata,
      only.clustering.markers = only.clustering.markers,
      acquired_markers = acquired_markers,
      markers = markers,
      elapsed_seconds = proc.time()[["elapsed"]] - start_time,
      diptest_args = diptest_args,
      max.n.diptest = max.n.diptest,
      seed = seed,
      target = target
    )

    return(new_inflect_results(
      collection.U = diagnostic.graph$collection.U,
      fittedcurve = diagnostic.graph$fittedcurve,
      lfunction = diagnostic.graph$lfunction,
      ggplot = diagnostic.graph$ggplot,
      metaclustering.list = metaclustering.list,
      accuracy.sets = collection.U[["Accuracy.matrixes"]],
      selection = selection,
      provenance = provenance
    ))
  }
