#' @title Run unimodality quality control on metaclusterings in parallel
#'
#' @description Unimodality score is calculated for all calculated metaclusterings.
#'
#' @param FlowSOM.results A FlowSOM object with completed SOM clustering, either after full FlowSOM function or after BuildSOM
#' @param metaclustering.list List of metaclustering results, as generated by \link{iteration.metacluster}
#' @param set.i Vector containing either the desired iterations to be tested
#' @param multicore logical, should INFLECT be run in parallel using \link[doParallel]{registerDoParallel}. Default is \code{TRUE}
#' @param cores If \code{multicore == TRUE}, number of cores to be used. If \code{NULL} max number of cores-1 is used.
#' @param zeroes.in Should be values at and below \code{0} be included. Recommeded default for mass cytometry data is \code{FALSE}
#' @param only.clustering.markers If \code{TRUE} only evaluates markers specified in FlowSOM.results$map$colsUsed
#' @param acquired_markers Vector of column names with marker data to be evaluated by INFLECT. Ignored if \code{only.clustering.markers == TRUE}
#' @param uniform.test What tests are performed per marker per cluster. Options are "both", "spread" , or "unimodality" as a string.
#' @param th.pvalue Threshold for rejecting Unimodality dip.test result. Default is \code{0.05}. For more information see \link[diptest]{dip.test}
#' @param th.IQR Threshold for rejecting marker distribution based on inter-quartile range. Default is arc-sinh transformed value of \code{2}.
#' @param verbose \code{logical} , default is \code{FALSE}
#' @param ... Additional arguments to pass to \code{\link[diptest]{dip.test}} through \code{\link{FlowSOMQC}}.
#'
#' @return A \code{list} with 2 items. The first is the unimodality scores stored in U.set. Second is a \code{list} with a \code{logical} matrix for each metaclustering result.
#' @seealso \code{\link{INFLECT}}, \code{\link{iteration.metacluster}}, \code{\link{FlowSOMQC}}
#'
#' @export
iteration.QC <- function(FlowSOM.results,
                         metaclustering.list,
                         set.i,
                         multicore = TRUE,
                         cores = NULL,
                         zeroes.in = FALSE,
                         only.clustering.markers = TRUE,
                         acquired_markers = NULL,
                         uniform.test = c("both", "spread", "unimodality"),
                         th.pvalue = 0.05,
                         th.IQR = 2,
                         verbose = FALSE,
                         ...) {
  uniform.test <- match.arg(uniform.test)

  run_qc <- function(Ui) {
    metaclustering <- metaclustering.list[[as.character(Ui)]]
    accuracy.matrix <- FlowSOMQC(
      FlowSOM.results = FlowSOM.results,
      metaclustering = metaclustering,
      zeroes.in = zeroes.in,
      only.clustering.markers = only.clustering.markers,
      acquired_markers = acquired_markers,
      uniform.test = uniform.test,
      th.pvalue = th.pvalue,
      th.IQR = th.IQR,
      verbose = verbose,
      ...
    )
    list(
      accuracy.matrix = accuracy.matrix,
      score = sum(accuracy.matrix, na.rm = TRUE) * 100 / prod(dim(accuracy.matrix))
    )
  }

  if (multicore) {
    if (is.null(cores)) {
      cores <- max(1, parallel::detectCores() - 1)
    }
    cluster <- parallel::makeCluster(cores)
    on.exit(parallel::stopCluster(cluster), add = TRUE)
    doParallel::registerDoParallel(cluster)

    qc.results <- foreach::foreach(
      Ui = set.i,
      .final = function(x) stats::setNames(x, as.character(set.i)),
      .export = "FlowSOMQC",
      .packages = c("diptest", "gtools")
    ) %dopar% {
      run_qc(Ui)
    }
  } else {
    qc.results <- stats::setNames(lapply(set.i, run_qc), as.character(set.i))
  }

  accuracy.set <- lapply(qc.results, `[[`, "accuracy.matrix")
  accuracy.set <- stats::setNames(accuracy.set, names(qc.results))
  U.values <- vapply(qc.results, `[[`, numeric(1), "score")
  U.set <- data.frame(
    i = as.numeric(names(U.values)),
    Unimodality = unname(U.values)
  )

  return(list("U.set" = U.set, "Accuracy.matrixes" = accuracy.set))
}
