#' @title Run unimodality quality control on metaclusterings in parallel
#'
#' @description Unimodality scores are computed for all metaclusterings in
#' `set.i`. Each distinct SOM-node subtree is evaluated once; the per-k
#' accuracy matrices are assembled from that cache. The marker-level pass/fail
#' definition is aligned with the original `FlowSOMQC()` method.
#'
#' @param FlowSOM.results A supported SOM object with completed SOM clustering. Supports \pkg{FlowSOM} objects and \pkg{kohonen} objects returned by \code{\link[kohonen]{som}} or \code{\link[kohonen]{xyf}}.
#' @param metaclustering.list List of metaclustering results, as generated by \link{iteration.metacluster}
#' @param set.i Vector containing either the desired iterations to be tested
#' @param multicore logical, should the QC sweep be run in parallel (fork-based \code{\link[parallel]{mclapply}} over distinct SOM-node subtrees on Unix). Ignored on Windows. Default is \code{TRUE}
#' @param cores If \code{multicore == TRUE}, number of cores to be used. If \code{NULL} max number of cores-1 is used.
#' @param zeroes.in Should be values at and below \code{0} be included. Recommended default for mass cytometry data is \code{FALSE}
#' @param only.clustering.markers If \code{TRUE} only evaluates markers specified as clustering markers. For \pkg{kohonen} objects this is the first data layer.
#' @param acquired_markers Vector of column names with marker data to be evaluated by fastINFLECT. Ignored if \code{only.clustering.markers == TRUE}
#' @param uniform.test What tests are performed per marker per cluster. Options are "both", "spread" , or "unimodality" as a string.
#' @param th.pvalue Threshold for rejecting Unimodality dip.test result. Default is \code{0.05}. For more information see \link[diptest]{dip.test}
#' @param th.IQR Threshold for rejecting marker distribution based on inter-quartile range. Default is arc-sinh transformed value of \code{2}.
#' @param max.n.diptest Optional integer. If set, each (cluster, marker) sample is randomly subsampled to at most this many events before the dip test. This removes the sample-size sensitivity of the dip test (large clusters otherwise make it reject unimodality for trivial deviations) at the cost of direct legacy-score comparability. Subsampling is seeded and therefore deterministic. Default \code{NULL} preserves the legacy scoring path.
#' @param seed Integer base seed used for the optional subsampling. Default \code{1L}.
#' @param verbose \code{logical} , default is \code{FALSE}
#' @param ... Additional arguments to pass to \code{\link[diptest]{dip.test}} through \code{\link{FlowSOMQC}}.
#'
#' @return A \code{list} with 2 items. The first is the unimodality scores stored in U.set. Second is a \code{list} with a \code{logical} matrix for each metaclustering result.
#' @seealso \code{\link{INFLECT}}, \code{\link{iteration.metacluster}}, \code{\link{FlowSOMQC}}
#'
#' @export
iteration.QC <- function(FlowSOM.results,
                         metaclustering.list,
                         set.i,
                         multicore = TRUE,
                         cores = NULL,
                         zeroes.in = FALSE,
                         only.clustering.markers = TRUE,
                         acquired_markers = NULL,
                         uniform.test = c("both", "spread", "unimodality"),
                         th.pvalue = 0.05,
                         th.IQR = 2,
  verbose = FALSE,
  max.n.diptest = NULL,
  seed = 1L,
  ...) {
  uniform.test <- match.arg(uniform.test)
  max.n.diptest <- .inflect_validate_max_n_diptest(max.n.diptest)
  view <- as_inflect_som(FlowSOM.results)
  n_nodes <- as.integer(view$map$nNodes)

  prep <- .inflect_prepare_qc(
    view = view,
    only.clustering.markers = only.clustering.markers,
    acquired_markers = acquired_markers
  )
  p_of <- .inflect_make_p_of(list(...))

  ## Events grouped by SOM node once; a metacluster's events are the union of its
  ## member nodes' events, so QC depends only on the node set, not on k.
  node_events <- split(
    seq_len(nrow(prep$data)),
    factor(prep$mapping, levels = seq_len(n_nodes))
  )

  ## 1. Enumerate every metacluster across all k, keyed by its sorted SOM-node set.
  ##    Distinct keys are the only QC evaluations that actually differ; for a nested
  ##    (hierarchical) sweep there are at most 2 * n_nodes - 1 of them regardless of
  ##    how densely set.i samples k.
  keys_per_k <- vector("list", length(set.i))
  names(keys_per_k) <- as.character(set.i)
  unique_members <- list()
  for (Ui in set.i) {
    mc <- .inflect_normalize_metaclustering(
      metaclustering = metaclustering.list[[as.character(Ui)]],
      n_nodes = n_nodes,
      label = paste0("`metaclustering.list[['", Ui, "']]`")
    )
    metaclustering.list[[as.character(Ui)]] <- mc
    n_clusters <- max(mc)
    ks <- character(n_clusters)
    for (cl in seq_len(n_clusters)) {
      nodes <- which(mc == cl)
      key <- paste0(nodes, collapse = ",")   # which() is increasing -> canonical
      ks[cl] <- key
      if (is.null(unique_members[[key]])) {
        unique_members[[key]] <- nodes
      }
    }
    keys_per_k[[as.character(Ui)]] <- ks
  }

  ## 2. Evaluate each distinct node set exactly once. When max.n.diptest caps the
  ##    sample, the per-key seed offset keeps every cell's subsample deterministic
  ##    (and, because each key is evaluated once, stable across all k).
  keys <- names(unique_members)
  eval_one <- function(idx) {
    nodes <- unique_members[[keys[idx]]]
    rows <- if (length(nodes)) unlist(node_events[nodes], use.names = FALSE) else integer(0)
    expr <- prep$data[rows, , drop = FALSE]
    .inflect_accuracy_row(
      expr = expr,
      zeroes.in = zeroes.in,
      uniform.test = uniform.test,
      th.pvalue = th.pvalue,
      th.IQR = th.IQR,
      p_of = p_of,
      subsample = max.n.diptest,
      seed = seed + idx * 100L
    )
  }

  use_parallel <- isTRUE(multicore) &&
    length(keys) > 1L &&
    .Platform$OS.type == "unix"
  if (use_parallel) {
    if (is.null(cores)) {
      cores <- max(1, parallel::detectCores() - 1)
    }
    rows_list <- parallel::mclapply(seq_along(keys), eval_one, mc.cores = cores)
  } else {
    rows_list <- lapply(seq_along(keys), eval_one)
  }
  names(rows_list) <- keys

  ## 3. Assemble per-k accuracy matrices and unimodality scores from the cache.
  ordered.markers <- prep$ordered.markers
  n_markers <- length(ordered.markers)
  accuracy.set <- vector("list", length(set.i))
  names(accuracy.set) <- as.character(set.i)
  U.values <- numeric(length(set.i))
  for (idx in seq_along(set.i)) {
    ks <- keys_per_k[[idx]]
    if (verbose) {
      message("Metaclustering k=", set.i[idx], ": ", length(ks), " clusters")
    }
    mat <- do.call(rbind, rows_list[ks])
    dimnames(mat) <- list(seq_along(ks), ordered.markers)
    accuracy.set[[idx]] <- mat
    U.values[idx] <- sum(mat, na.rm = TRUE) * 100 / (length(ks) * n_markers)
  }

  U.set <- data.frame(
    i = as.numeric(set.i),
    Unimodality = U.values
  )

  return(list("U.set" = U.set, "Accuracy.matrixes" = accuracy.set))
}
