# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.inflect_iqr_cpp <- function(x) {
    .Call(`_fastINFLECT_inflect_iqr_cpp`, x)
}

.inflect_dip_pvalue_cpp <- function(D, n, qd, nn, Ps) {
    .Call(`_fastINFLECT_inflect_dip_pvalue_cpp`, D, n, qd, nn, Ps)
}

